services:
   vprodb:
      build:
         context: ./Docker-files/db
      image: utkumar22/uprofiledb
      container_name: vprodb
      ports:
        - "3306:3306"
      volumes:
        - /var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=vprodbpass

   vprocache01:
      
      image: memcached
      container_name: vprocache01
      ports:
        - "11211:11211"

   vpromq01:
      
      image: rabbitmq
      ports:
        - "5672:5672"
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest


   vproapp:
      build:
         context: ./Docker-files/app
      image: utkumar22/uprofileapp
      container_name: vproapp
      ports:
        - "8080:8080"
      volumes:
        - /usr/local/tomcat/webapps

   vproweb:
      build:
         context: ./Docker-files/web
      image: utkumar22/uprofileweb
      container_name: vproweb
      ports:
        - "80:80"
      
         

volumes:
   vprodbdata: {}
   vproappdata: {}
